//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public System.DateTime TakeOffDate { get; set; }
        public System.DateTime LandingDate { get; set; }
        public string PlaneType { get; set; }
        public string PlaneID { get; set; }
        public string PilotName { get; set; }
        public int FreePassangersSeats { get; set; }
        public int FreeBusinessSeats { get; set; }
    }
}
